# SET (grib file)

Generally hard to use

In [1]:
!pip install -q condacolab
import condacolab
condacolab.install()

✨🍰✨ Everything looks OK!


In [2]:
!conda --version
!which conda

conda 4.11.0
/usr/local/bin/conda


In [3]:
!conda install metview -c conda-forge
!conda update metview -c conda-forge

Solving environment: / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done

# All requested packages already installed.

Solving environment: / - \ | / - \ | / - \ | / - \ failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / 

`metview` is .... poorly maintained
spent hours and hours solving dependency issues/bugs

use NASA's H5 datasets as much as possible

In [4]:
!pip install metview

In [5]:
%%bash
wget --output-document=SET_sample.grib https://github.com/hohohohia/misc/blob/main/SET_sample.grib?raw=true
wget --output-document=SMAP_test.h5 https://github.com/hohohohia/misc/blob/main/SMAP_test.h5?raw=true

--2022-02-26 18:43:35--  https://github.com/hohohohia/misc/blob/main/SET_sample.grib?raw=true
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/hohohohia/misc/raw/main/SET_sample.grib [following]
--2022-02-26 18:43:35--  https://github.com/hohohohia/misc/raw/main/SET_sample.grib
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hohohohia/misc/main/SET_sample.grib [following]
--2022-02-26 18:43:35--  https://raw.githubusercontent.com/hohohohia/misc/main/SET_sample.grib
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7449240

In [6]:
import metview as mv

In [7]:
filename = "SET_sample.grib"
if mv.exist(filename):
    wg = mv.read(filename)
else:
    wg = mv.gallery.load_dataset(filename)
print(wg)
print(len(wg))

Fieldset (1 field)
1


In [8]:
mv.grib_get(wg, ['shortName', 'dataDate', 'dataTime',
                 'stepRange', 'validityDate', 'validityTime'])

[['e', '20160101', '0000', '0-1', '20160101', '100']]

In [9]:
print(mv.minvalue(wg), mv.maxvalue(wg))

-0.0010228018509224057 0.00013241998385637999


In [10]:
v = mv.values(wg)
v.shape

(6483600,)

In [11]:
all_maxes = [mv.maxvalue(f) for f in wg]
all_maxes
wg0 = wg[0]
max0 = all_maxes[0]
max_location = mv.find(wg0, max0)
max_location

[[62.10000000000145, 35.00000000000023]]

In [12]:
mv.setoutput('jupyter')
mv.plot(wg[0], mv.mcont(contour_automatic_setting='ecmwf'))

Image(value=b'', layout="Layout(visibility='hidden')")

Label(value='Generating plots....')

In [13]:
! python -m pip install xarray

     |████████████████████████████████| 845 kB 5.1 MB/s 


In [14]:
%%bash
pip install xarray

In [16]:
fs = mv.read(source="SET_sample.grib")

# SMAP (h5 file)

Can be conveniently transformed into pandas dataframes

In [17]:
!pip install "basemap == 1.3.0b1" "basemap-data == 1.3.0b1"
!pip install basemap
!pip install matplotlib==3.1.3

     |████████████████████████████████| 881 kB 4.9 MB/s 
     |████████████████████████████████| 30.5 MB 2.0 MB/s 
     |████████████████████████████████| 219 kB 44.2 MB/s 
     |████████████████████████████████| 6.3 MB 49.1 MB/s 
     |████████████████████████████████| 10.3 MB 15.3 MB/s 
     |████████████████████████████████| 4.3 MB 49.4 MB/s 
     |████████████████████████████████| 1.1 MB 41.9 MB/s 
     |████████████████████████████████| 98 kB 6.7 MB/s 
  Created wheel for pyshp: filename=pyshp-2.1.3-py3-none-any.whl size=37324 sha256=384714ded37075f872b2dfd446ba7e84de1ec46f883455bd48dd66169793b015
  Stored in directory: /root/.cache/pip/wheels/43/f8/87/53c8cd41545ba20e536ea29a8fcb5431b5f477ca50d5dffbbe
Successfully built pyshp
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0


     |████████████████████████████████| 13.1 MB 133 kB/s 
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.4.3
    Uninstalling matplotlib-3.4.3:
      Successfully uninstalled matplotlib-3.4.3


In [19]:
import datetime as dt
import glob
import h5py
%matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap
import numpy as np
import os
import pandas as pd
#import xarray as xr

In [20]:
filename='SMAP_test.h5'
f = h5py.File(filename, 'r')
print(f); print('\n')

<HDF5 file "SMAP_test.h5" (mode r)>




In [21]:
#Now lets look at the groups within the file to access
i=0;
for key in f.keys():
    print(str(i)+ '\t'+key)
    i+=1
group_id=list(f.keys())[1]


0	Metadata
1	Soil_Moisture_Retrieval_Data
2	Soil_Moisture_Retrieval_Data_Polar


In [22]:
print('\n')
i=0
for var in list(f[group_id].keys()):
    print(str(i)+'\t'+var)
    i+=1



0	EASE_column_index
1	EASE_row_index
2	albedo
3	albedo_option3
4	boresight_incidence
5	bulk_density
6	clay_fraction
7	freeze_thaw_fraction
8	grid_surface_status
9	latitude
10	latitude_centroid
11	longitude
12	longitude_centroid
13	organic_content
14	radar_water_body_fraction
15	retrieval_qual_flag
16	retrieval_qual_flag_option1
17	retrieval_qual_flag_option2
18	retrieval_qual_flag_option3
19	roughness_coefficient
20	roughness_coefficient_option3
21	sand_fraction
22	soil_moisture
23	soil_moisture_error
24	soil_moisture_option1
25	soil_moisture_option2
26	soil_moisture_option3
27	static_water_body_fraction
28	surface_flag
29	surface_temperature
30	surface_water_fraction_mb_h
31	surface_water_fraction_mb_v
32	tb_3_corrected
33	tb_4_corrected
34	tb_h_corrected
35	tb_h_uncorrected
36	tb_qual_flag_3
37	tb_qual_flag_4
38	tb_qual_flag_h
39	tb_qual_flag_v
40	tb_time_seconds
41	tb_time_utc
42	tb_v_corrected
43	tb_v_uncorrected
44	vegetation_opacity
45	vegetation_opacity_option1
46	vegetation_o

In [23]:
print('the data has a shape of: '+str(f[group_id][list(f[group_id].keys())[0]].shape))

the data has a shape of: (272372,)


In [24]:
var_id = list(f[group_id].keys())[22] # soil_moisture
sm_data = f[group_id][var_id][:]
sm_ds = f[group_id][var_id]

var_id = list(f[group_id].keys())[10] # soil_moisture
lati = f[group_id][var_id][:]

var_id = list(f[group_id].keys())[12] # soil_moisture
longi = f[group_id][var_id][:]

print('data are returned as '+str(type(sm_data)))

data are returned as <class 'numpy.ndarray'>


In [25]:
sm_ds,sm_data,lati,longi

(<HDF5 dataset "soil_moisture": shape (272372,), type "<f4">,
 array([-9999., -9999., -9999., ..., -9999., -9999., -9999.], dtype=float32),
 array([-65.229836, -65.39704 , -65.56531 , ..., -81.71884 , -82.2176  ,
        -82.75034 ], dtype=float32),
 array([-179.95332, -179.95332, -179.95332, ...,  179.95332,  179.95332,
         179.95332], dtype=float32))

In [26]:
df=pd.DataFrame(np.transpose([sm_data,lati,longi]),columns=['moisture', 'lati', 'longi'])
df

moisture       lati       longi
0        -9999.0 -65.229836 -179.953323
1        -9999.0 -65.397041 -179.953323
2        -9999.0 -65.565308 -179.953323
3        -9999.0 -65.734665 -179.953323
4        -9999.0 -65.905144 -179.953323
...          ...        ...         ...
272367   -9999.0 -80.801537  179.953323
272368   -9999.0 -81.248268  179.953323
272369   -9999.0 -81.718842  179.953323
272370   -9999.0 -82.217598  179.953323
272371   -9999.0 -82.750343  179.953323

[272372 rows x 3 columns]

In [27]:
moist=df.moisture.to_numpy()
np.max(moist)

0.73955464